apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}  #q2-web-app
spec:
  replicas: {{ .Values.replicaCount }} # 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: q2-web-app
  template:
    metadata:
      labels:
        app: q2-web-app
    spec:
      containers:
      - name: q2-web-app
        image: 1292003/finalexam:latest
        ports:
        - containerPort: 8080
