
apiVersion: v1
kind: Service
metadata:
  name: q2-web-ap
  labels:
    app: q2-web-app
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30039
    targetPort: 80
    protocol: TCP
  selector:
    app: q2-web-app
